import { useNavigate } from "react-router-dom";
import Hero from "../components/Hero";
import Button from "../components/Button";

const Home = () => {
    const navigate = useNavigate();

    return (
        <div className="bg-white">
            <Hero />
            <div className="bg-white py-24 sm:py-32">
                <div className="mx-auto max-w-7xl px-6 lg:px-8">
                    <div className="mx-auto max-w-2xl text-center">
                        <h2 className="text-base font-semibold leading-7 text-blue-600">Smart Features</h2>
                        <p className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Everything you need for your trip</p>
                        <p className="mt-6 text-lg leading-8 text-gray-600">
                            From discovering hidden gems to managing your itinerary and budget, we've got you covered.
                        </p>
                    </div>
                    <div className="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-none">
                        <dl className="grid max-w-xl grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-3">
                            {[
                                {
                                    name: 'AI Itinerary Generator',
                                    description: 'Let our AI create a perfect, personalized itinerary based on your preferences, budget, and time constraints.',
                                    icon: '✨',
                                },
                                {
                                    name: 'Smart Budgeting',
                                    description: 'Plan your expenses and stay within budget with our intuitive financial tools that track every penny.',
                                    icon: '💰',
                                },
                                {
                                    name: 'Discover Destinations',
                                    description: 'Explore curated destinations with detailed guides, authentic tips, and hidden gems you won\'t find elsewhere.',
                                    icon: '🌍',
                                },
                                {
                                    name: 'Weather Forecasts',
                                    description: 'Stay prepared with accurate weather predictions for your travel dates to pack smartly.',
                                    icon: '☀️',
                                },
                                {
                                    name: 'Packing Assistant',
                                    description: 'Get customized packing lists generated by AI based on your destination and planned activities.',
                                    icon: '🎒',
                                },
                                {
                                    name: 'Activity Booking',
                                    description: 'Seamlessly book tours, museum tickets, and other adventures directly from your itinerary.',
                                    icon: '🎟️',
                                },
                            ].map((feature) => (
                                <div key={feature.name} className="flex flex-col bg-gray-50 rounded-2xl p-8 hover:bg-gray-100 transition-colors">
                                    <dt className="flex items-center gap-x-3 text-base font-semibold leading-7 text-gray-900">
                                        <span className="text-3xl bg-white rounded-lg p-2 shadow-sm">{feature.icon}</span>
                                        {feature.name}
                                    </dt>
                                    <dd className="mt-4 flex flex-auto flex-col text-base leading-7 text-gray-600">
                                        <p className="flex-auto">{feature.description}</p>
                                    </dd>
                                </div>
                            ))}
                        </dl>
                    </div>
                </div>
            </div>

            {/* CTA Section */}
            <div className="bg-blue-600">
                <div className="px-6 py-24 sm:px-6 sm:py-32 lg:px-8">
                    <div className="mx-auto max-w-2xl text-center">
                        <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
                            Ready to explore the world?
                            <br />
                            Start planning your trip today.
                        </h2>
                        <p className="mx-auto mt-6 max-w-xl text-lg leading-8 text-blue-100">
                            Join thousands of travelers who use AiTravel to create unforgettable memories. No credit card required.
                        </p>
                        <div className="mt-10 flex items-center justify-center gap-x-6">
                            <a
                                href="/register"
                                className="rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-blue-600 shadow-sm hover:bg-blue-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
                            >
                                Get started
                            </a>
                            <a href="/destinations" className="text-sm font-semibold leading-6 text-white">
                                Learn more <span aria-hidden="true">→</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Home;
